### ISSUE TITLE
Docking graph window stop unity to open again

### ISSUE THREAD

**Issue by CoffeSan** [CoffeeVampir3/Graphify#72]
hi how are you ?, i think i found a bug, when i close the unity with the graph window, and open the unity again, it does not start and shows [this error](https://i.imgur.com/BjZrtIo.png). I can only enter the editor when I delete CurrentLayout-default.dwlt and EditorSnapSettings.asset, in the project/Library folder.

https://www.youtube.com/watch?v=tTY_DEFtABU

Not sure and there is a problem with my version of Unity (2020.3.8f1)

**Comment by CoffeeVampir3** [comment]
Heya,

I am not able to test the issue at the moment, but I have a suspiscion that unity is hanging on to an invalid serialized reference from the editor window, specifically 
`[SerializeReference] protected GraphifyView graphView;`

I've pushed a hotfix to the GraphifyWindow class that unloads the reference during OnDisable and OnDestroy which I'm hoping should correct the issue.

Let me know if this issue continues after updating.

**Comment by CoffeSan** [comment]
I updated my project with the new version but it still gives the same error. I downloaded the source code, to try to fix the error, if I find any solution I do a PR
